// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvalDbContext))]
    [Migration("20260713155549_AddFoldersAndPromptOwnedDatasets")]
    partial class AddFoldersAndPromptOwnedDatasets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("Domain.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("eval_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Domain.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("Domain.ScorerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("scorer_configs", (string)null);
                });

            modelBuilder.Entity("Domain.Dataset", b =>
                {
                    b.HasOne("Domain.Prompt", null)
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Fixture", "Fixtures", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("DatasetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExpectedOutput")
                                .HasColumnType("text");

                            b1.Property<string>("Input")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("SeedFixtureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UpstreamContext")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("DatasetId");

                            b1.ToTable("fixtures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DatasetId");
                        });

                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("Domain.EvalRun", b =>
                {
                    b.OwnsMany("Domain.FixtureRun", "Results", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("CostUsd")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("EvalRunId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("FixtureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("LatencyMs")
                                .HasColumnType("integer");

                            b1.Property<string>("ModelOutput")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("EvalRunId");

                            b1.ToTable("fixture_runs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EvalRunId");

                            b1.OwnsMany("Domain.Score", "Scores", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Detail")
                                        .HasColumnType("text");

                                    b2.Property<Guid>("FixtureRunId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool?>("Passed")
                                        .HasColumnType("boolean");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FixtureRunId");

                                    b2.ToTable("scores", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("FixtureRunId");

                                    b2.OwnsOne("Domain.ScorerDescriptor", "Scorer", b3 =>
                                        {
                                            b3.Property<Guid>("ScoreId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Config")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("scorer_config");

                                            b3.Property<string>("JudgeModel")
                                                .HasColumnType("text")
                                                .HasColumnName("judge_model");

                                            b3.Property<string>("Kind")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("scorer_kind");

                                            b3.HasKey("ScoreId");

                                            b3.ToTable("scores");

                                            b3.WithOwner()
                                                .HasForeignKey("ScoreId");
                                        });

                                    b2.Navigation("Scorer")
                                        .IsRequired();
                                });

                            b1.Navigation("Scores");
                        });

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Domain.Folder", b =>
                {
                    b.HasOne("Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Prompt", b =>
                {
                    b.HasOne("Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Domain.PromptVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Label")
                                .HasColumnType("text");

                            b1.Property<Guid>("PromptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SourceApp")
                                .HasColumnType("text");

                            b1.Property<string>("TargetModel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PromptId");

                            b1.ToTable("prompt_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PromptId");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Domain.ScorerConfig", b =>
                {
                    b.OwnsOne("Domain.ScorerDescriptor", "Scorer", b1 =>
                        {
                            b1.Property<Guid>("ScorerConfigId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Config")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scorer_config");

                            b1.Property<string>("JudgeModel")
                                .HasColumnType("text")
                                .HasColumnName("judge_model");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scorer_kind");

                            b1.HasKey("ScorerConfigId");

                            b1.ToTable("scorer_configs");

                            b1.WithOwner()
                                .HasForeignKey("ScorerConfigId");
                        });

                    b.Navigation("Scorer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
