// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvalDbContext))]
    [Migration("20260712150350_AddPromptRegistry")]
    partial class AddPromptRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("eval_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("Domain.Prompt", b =>
                {
                    b.OwnsMany("Domain.PromptVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Label")
                                .HasColumnType("text");

                            b1.Property<Guid>("PromptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SourceApp")
                                .HasColumnType("text");

                            b1.Property<string>("TargetModel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PromptId");

                            b1.ToTable("prompt_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PromptId");
                        });

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
